#!/bin/bash

TEMP_STATE="/tmp/transparency-state"
PERSISTENT_STATE="$HOME/.cache/transparency-state"

[ -f "$TEMP_STATE" ] && exit 0

if [ -f "$PERSISTENT_STATE" ]; then
    cp "$PERSISTENT_STATE" "$TEMP_STATE"
else
    printf 'transparent\n' > "$TEMP_STATE"
    printf 'transparent\n' > "$PERSISTENT_STATE"
fi
