github.com:
    users:
        Yeastiest:
            oauth_token: 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
    git_protocol: https
    user: Yeastiest
    oauth_token: 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
