#!/usr/bin/env bash
wallpaper="${1#*$'\x1f'}"

theme=$(~/.config/scripts/images-photos-wallpapers/wallpaper-theme-picker)
[[ -z "$theme" ]] && exit 0

fzfub-wallpapermenu "theme-only" "$theme"
fzfub-wallpaper-save "$wallpaper" theme "$theme"
