#!/bin/sh

# ueberzugpp stuff
case "$(uname -a)" in
*Darwin*) UEBERZUG_TMP_DIR="$TMPDIR" ;;
*) UEBERZUG_TMP_DIR="/tmp" ;;
esac

cleanup() {
  ueberzugpp cmd -s "$SOCKET" -a exit
}
trap cleanup HUP INT QUIT TERM EXIT

UB_PID_FILE="$UEBERZUG_TMP_DIR/.$(uuidgen)"
ueberzugpp layer --no-stdin --silent --pid-file "$UB_PID_FILE" 2>/dev/null
UB_PID=$(cat "$UB_PID_FILE")

export SOCKET="$UEBERZUG_TMP_DIR"/ueberzugpp-"$UB_PID".socket

# fzf optional settings:
# first argument: directory
# second argument: preset options
# third argument: any other options
# example using wallpapermenu opts:
# fzfub ~/pics w --tac

case $2 in
*x) # image picker (wallpaper + clipboard)
  FZFARGS='enter:execute-silent(wallpapermenu {}),ctrl-w:execute-silent(wallpapermenu {}),ctrl-c:execute(cliphist write-image {} | cliphist add && notify-send "Copied to clipboard")+reload(cliphist list-images),ctrl-e:become(gimp {+} > /dev/null 2>&1)'
  ILABEL='Image Picker'
  LABEL='[enter/*w*allpaper  *c*lipboard  *e*dit-gimp]'
  IMGFILTER='yes'
  ;;
*w) # wallpapermenu options
  FZFARGS='enter:execute-silent(fzfub-wallpaper-dark {}),ctrl-l:execute-silent(fzfub-wallpaper-light {}),ctrl-f:execute-silent(fzfub-wallpaper-medium {}),ctrl-b:execute-silent(fzfub-wallpaper-only {}),ctrl-w:execute-silent(fzfub-wallpaper-dark {}),ctrl-e:become(gimp {+} > /dev/null 2>&1),ctrl-d:ignore'
  ILABEL='Wallpaper Menu'
  LABEL='[enter/*d*ark  *l*ight  ctrl-*f* medium  ctrl-*b* only  *e*dit-gimp]'
  IMGFILTER='yes'
  ;;
*m) # ₊⊹ɪᴍɢᴍɢᴋ⊹₊ options
  FZFARGS='ctrl-r:become(fzfubrefresh {}),ctrl-e:execute-silent(imgmgk stripexif {})+become(fzfubrefresh {}),alt-j:execute-silent(imgmgk jpg {})+become(fzfubrefresh {}),alt-p:execute-silent(imgmgk png {})+become(fzfubrefresh {}),ctrl-d:execute(rm -i {} && notify-send {} deleted)+become(fzfubrefresh {}),ctrl-s:execute-silent(imgmgk scale {+})+become(fzfubrefresh {}),ctrl-b:execute-silent(imgmgk bw {+})+become(fzfubrefresh {}),ctrl-w:execute-silent(imgmgk wm {+})+become(fzfubrefresh {}),ctrl-g:become(gimp {+} > /dev/null 2>&1),ctrl-t:execute-silent(imgmgk transparency {+})+become(fzfubrefresh {}),ctrl-f:execute-silent(imgmgk flip {+})+become(fzfubrefresh {}),ctrl-v:execute-silent(imgmgk vflip {+})+become(fzfubrefresh {}),ctrl-l:execute-silent(imgmgk border {+})+become(fzfubrefresh {}),ctrl-h:execute-silent(imgmgk wborder {+})+become(fzfubrefresh {})'
  ILABEL="Image Editor (alt: jpg/png | ctrl: delete/exif/bw/watermark)"
  LABEL="[*g*→gimp *t*ransparent *f*/*v*flip *l*black/*h*white border]"
  IMGFILTER='yes'
  ;;
*c) # cliphist options
  ILABEL="Clipboard: enter/*c*opy"
  LABEL="[*d*elete  *g*imp]"
  FZFARGS='enter:execute(cliphist copy {}),ctrl-c:execute(cliphist copy {}),ctrl-d:execute(rm {} && notify-send {} deleted),ctrl-g:become(gimp {+} > /dev/null 2>&1)'
  IMGFILTER='yes'
  ;;
*) FZFARGS='ctrl-d:execute(rm -i {} && notify-send {} deleted)' ;; # normal options
esac

# run fzf with preview and given vars
if [ "$IMGFILTER" = "yes" ]; then
	find "${1:-.}" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" -o -iname "*.webp" \) | \
	fzf $3 -m --bind "$FZFARGS" --style ${STYLE:-full} --reverse --preview-border --preview-label "$LABEL" --input-label "$ILABEL" --preview="ueberzugpp cmd -s $SOCKET -i fzfpreview -a add \
                             -x \$FZF_PREVIEW_LEFT -y \$FZF_PREVIEW_TOP \
                             --max-width \$FZF_PREVIEW_COLUMNS --max-height \$FZF_PREVIEW_LINES \
                             -f {} 2>/dev/null || bat --style=plain --color=always {}"
else
	fzf --walker-root=${1:-$PWD} $3 -m --bind "$FZFARGS" --style ${STYLE:-full} --reverse --preview-border --preview-label "$LABEL" --input-label "$ILABEL" --preview="ueberzugpp cmd -s $SOCKET -i fzfpreview -a add \
                             -x \$FZF_PREVIEW_LEFT -y \$FZF_PREVIEW_TOP \
                             --max-width \$FZF_PREVIEW_COLUMNS --max-height \$FZF_PREVIEW_LINES \
                             -f {} 2>/dev/null || bat --style=plain --color=always {}"
fi

ueberzugpp cmd -s "$SOCKET" -a exit
