#!/usr/bin/env bash

# slightly scuffed wallpaper picker menu for use with pywal - uses nsxiv if installed, otherwise uses dmenu

FOLDER="$HOME/Pictures/wallpaper" # wallpaper folder
SCRIPT="/home/croc/.config/wal/hooks/colorscheme"

menu() {
  if command -v nsxiv >/dev/null; then
    CHOICE=$(nsxiv -otb "$FOLDER"/*)
  else
    FILES=$(/usr/bin/ls -1 "$FOLDER")
    CHOICE=$(printf "Random\n%s\n" "$FILES" | dmenu -i -p "Wallpaper: ")
  fi

  case $CHOICE in
  Random) wal -i "$FOLDER" -o "$SCRIPT" && echo "$(/usr/bin/ls -1 "$FOLDER" | shuf -n 1)" > "$HOME/.cache/wal/last_wallpaper" ;; # dmenu random option
  *.*) wal -i "$FOLDER/$CHOICE" -o "$SCRIPT" && echo "$CHOICE" > "$HOME/.cache/wal/last_wallpaper" ;;
  *) exit 0 ;;
  esac
}

# If given arguments:
# First argument will be used by pywal as wallpaper/dir path
# Second will be used as theme (use wal --theme to view built-in themes)

case "$#" in
0) menu ;;
1) wal -i "$1" -o "$SCRIPT" ;;
2) wal -i "$1" --theme $2 -o "$SCRIPT" ;;
*) exit 0 ;;
esac
