#!/usr/bin/dash

command -v bc >/dev/null || { notify-send "Error: bc not found"; exit 1; }

f_to_c () { \
    fahrenheit="$(echo "" | dmenu -c -sb "#bf616a" -nf "#bf616a" -p "Enter temperature in Fahrenheit: " <&-)"
    [ -z "$fahrenheit" ] && exit
    case "$fahrenheit" in
        -*.[0-9]*|[0-9]*.[0-9]*|-[0-9]*|[0-9]*) ;;
        *) notify-send "Error: Not a valid number"; exit 1 ;;
    esac
    celsius=$(printf "scale=2; (%s - 32) * 5/9\n" "$fahrenheit" | bc)
    notify-send -h string:bgcolor:#81a1c1 "$fahrenheit°F is equal to $celsius°C"
}


c_to_f() { \
    celsius="$(echo "" | dmenu -c -sb "#81a1c1" -nf "#81a1c1" -p "Enter temperature in Celsius: " <&-)"
    [ -z "$celsius" ] && exit
    case "$celsius" in
        -*.[0-9]*|[0-9]*.[0-9]*|-[0-9]*|[0-9]*) ;;
        *) notify-send "Error: Not a valid number"; exit 1 ;;
    esac
    fahrenheit=$(printf "scale=2; (%s * 9/5) + 32\n" "$celsius" | bc)
    notify-send -h string:bgcolor:#bf616a "$celsius°C is equal to $fahrenheit°F"
}


choice() { \
  choose=$(printf "Fahrenheit to Celsius\\nCelsius to Fahrenheit" | dmenu -c -l 2 -i -p "Convert from: ")
  case "$choose" in
    *Celsius) f_to_c ;;
    *Fahrenheit) c_to_f ;;
    *) exit;;
  esac
}

choice
