#!/usr/bin/env bash

histfile="$HOME/.cache/txtcliphist"
placeholder="<NEWLINE>"

highlight() {
  clip=$(xclip -o -selection clipboard 2>/dev/null) ;}

output() {
  clip=$(xclip -i -f -selection clipboard 2>/dev/null) ;}

write() {
  [ -f "$histfile" ] || mkdir -p "$(dirname "$histfile")"
  [ -f "$histfile" ] || touch $histfile
  [ -z "$clip" ] && exit 0
  multiline=$(echo "$clip" | sed ':a;N;$!ba;s/\n/'"$placeholder"'/g')
  grep -Fxq "$multiline" "$histfile" || echo "$multiline" >> "$histfile"
  notification=$(echo \"$multiline\") ;}

sel() {
   DMENU_COLORS=$(/home/croc/dotfiles/scripts/.config/scripts/helpers/dmenu-colors)
   selection=$(tac "$histfile" | dmenu $DMENU_COLORS -c -l 20 -i -p "Clipboard:" -fn "monospace:size=10")
   [ -n "$selection" ] && echo "$selection" | sed "s/$placeholder/\n/g" | xclip -i -selection clipboard && notification="Copied to clipboard!" ;}

case "$1" in
  add) highlight && write ;;
  out) output && write ;;
  sel) sel ;;
  *) printf "$0 | File: $histfile\n\nadd - add selection to history\nsel - select from history\n" ; exit 0 ;;
esac

[ -z "$notification" ] || notify-send "$notification"
