# Use "Shift+q" to quit instead of the default "q"
[keybindings]
"Shift+q" = "quit"
"q" = "noop"
# Escape key to quit
"Esc" = "back"
"Backspace" = "noop"

# Replace f1 f3 with 1 2 3
"1" = "queue"
"3" = "library"
"F1" = "noop"
"F3" = "noop"

# Album art (requires ncspot built with `cover` feature)
"m" = "focus cover"

"i" = "focus library"

# Start in cover view by default
initial_screen = "cover"

# Cover view options
