#!/bin/bash
export DISPLAY=:0
st -c "neofetch" -n "neofetch" -f "Iosevka Term:size=10" -T "Welcome" -e sh -c 'neofetch; zsh' &
sleep 0.2
WINDOW_ID=$(xdotool search --class "neofetch" 2>/dev/null | head -1)
[ -n "$WINDOW_ID" ] && xdotool windowsize "$WINDOW_ID" 571 426 && xdotool windowmove "$WINDOW_ID" 30 40

